route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'Prometheus'
            channel: '#alert'
            api_url: 'https://hooks.slack.com/services/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'
